### ISSUE TITLE
Error running "make -C src" on MacOS 11.2.3

### ISSUE THREAD

**Issue by noahtopper** [natasha-jeppu/Trace2Model#3]
I'm using MacOS 11.2.3 on a 2016 MacBook Pro, and I was trying to go through the Setup Instructions for Mac. I went through everything as shown with no issues, then on step 3, after running the fifth line "make -C src", I got a complex-looking error. Most of the process seems to run, then I see this:

![error1](https://user-images.githubusercontent.com/58488951/120861733-c69cf800-c555-11eb-90fc-89039c14f320.png)

If I try to move on with the other steps, 5 runs for a while, and then I see this:

![error2](https://user-images.githubusercontent.com/58488951/120862263-a7eb3100-c556-11eb-86e4-fd9149ee389f.png)

Notice in particular that is says "cbmc: command not found". So I think the first error definitely prevented cbmc from being built correctly. Any suggestions?

**Comment by natasha-jeppu** [comment]
This is an error in CBMC compilation. You can independently install CBMC from source using the instructions provided in [CBMC](https://github.com/diffblue/cbmc/blob/develop/COMPILING.md) and add the corresponding installation folder to PATH so that it is detected by the tool. Make sure you use the CBMC v5.11.
I believe it's an issue with the gcc compiler version. If possible, try setting it up in a linux docker container, the installation is much easier there.

**Comment by noahtopper** [comment]
> This is an error in CBMC compilation. You can independently install CBMC from source using the instructions provided in [CBMC](https://github.com/diffblue/cbmc/blob/develop/COMPILING.md) and add the corresponding installation folder to PATH so that it is detected by the tool. Make sure you use the CBMC v5.11.
> I believe it's an issue with the gcc compiler version. If possible, try setting it up in a linux docker container, the installation is much easier there.

I actually tried installing from https://www.cprover.org/cbmc/ and it looks like everything is working now. Thanks for the help!
